Added Kotlin "Support"
Jonxslays/Rick pull request #1
Opened 2022-01-14 11:31 UTC by Unicorn7141

2022-01-14 11:40 UTC, Unicorn7141 commented
Added also Dart 😅

2022-01-14 12:18 UTC, Jonxslays requested changes
The method names match what is being printed. The methods should be titled `never`, `gonna`, `give`, `you`, `up`. Can you correct that in both examples?

Blame me for not having contributing guidelines. 

Also, please remove the jar file from git. I would prefer to only host the source. 

This is awesome though, thanks for contributing :).

2022-01-14 12:47 UTC, Unicorn7141 commented
Done that (ignore the edited `.py` file, I accidentally touched it 😅

2022-01-15 11:58 UTC, Jonxslays approved these changes

2022-01-15 11:58 UTC, merged